### PR TITLE
Feature/5/custom paragraph

### PR DESCRIPTION
**Pull request by MichaelXian**
Created a custom field when creating/editing a page, which allows the user to have a paragraph at the top/bottom of the page, either below the header or above the footer (May be edited to below a title, but I don't see any titles yet.)

### CODE REVIEW

**Comment by sumeetgrewal** [comment]
please remove all IDE files

**Comment by MichaelXian** [comment]
Created the paragraph as an ACF. The ACF php file is under advanced-custom-fields/ and is included in functions.php Writing wiki now.

**Comment by MichaelXian** [comment]
Wiki written

**Comment by sumeetgrewal** [comment]
please remove acf-button-field

**Pull request merged**
